### ISSUE TITLE
The promtail binary used in the lib is dynamically linked

### ISSUE THREAD

**Issue by simskij** [canonical/loki-k8s-operator#107]
### Bug Description

The promtail binary currently used in the lib is dynamically linked. This means it won't work on all Linux environments. We need to build our own version from upstream that is statically linked (ie. with CGO disabled). The suggested course of action, for now, is to build it ourselves, place it in the Loki repo, and fetch it from there instead of directly from the upstream repo.

### To Reproduce

1. `wget https://github.com/grafana/loki/releases/download/v2.4.1/promtail-linux-amd64.zip`
2. `unzip promtail-linux-amd64.zip`
3. `file promtail-linux-amd64`

### Environment

N/A

### Relevant log output

```shell
❯ file promtail-linux-amd64

promtail-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=ZZTDSIbZy_VfnPWWwZOz/C9YTBAHGKginqRccK1ae/XVCFXE7cTRaMg17D9-Xy/drsoguGJyTXhi9FV8Vbu, BuildID[sha1]=c4e8062fc97a9e5fd59355a162aba1bab0609cac, stripped
```

**Comment by mmanciop** [comment]
I feel we should have a GitHub workflow in the `loki-k8s-operator` repo that tracks the latest Promtail release, checks out the code, builds it statically, and creates a similar release in `loki-k8s-operator` with the static Promtail binary.

**Comment by simskij** [comment]
> I feel we should have a GitHub workflow in the `loki-k8s-operator` repo that tracks the latest Promtail release, checks out the code, builds it statically, and creates a similar release in `loki-k8s-operator` with the static Promtail binary.

This is a very valid suggestion which I think we should do, once the most pressing issue (ie. OP) has been resolved.
