### ISSUE TITLE
The error when multiple containers are found and no container name is passed is poorly named

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#109]
Change the name to be MultipleContainersFoundError and clean up the error message

**Comment by mmanciop** [comment]
If there is precisely one container, yes, it is redundant.

if there are multiple containers, we should have the charm declare ONE logproxy (it’s coupled with the relation id), with Promtail installed in each of the listed containers. I am not sure this latter usecase is implemented.

**Comment by simskij** [comment]
Change the name to be `MultipleContainersFoundError` and clean up the error message

**Comment by simskij** [comment]
Also check whether the passed container name actually exists when one is supplied
