### ISSUE TITLE
Integrate loki_push_api with Ingress

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#116]
### Bug Description

Loki charmed in standalone mode must implement an ingress relation using the ingress_per_unit relation interface and the https://github.com/canonical/traefik-k8s-operator/blob/main/lib/charms/traefik_k8s/v0/ingress_per_unit.py  library. The URL received by Loki must be used to produce the URL of the Loki Push API endpoint, and the https://github.com/canonical/loki-k8s-operator/blob/ba1bd4176a83b6849c89c46137f39f1b7694cadc/lib/charms/loki_k8s/v0/loki_push_api.py#L1111. No tight coupling between the ingress and loki_push_api API is desired. LokiPushApiProvider must therefore be updated to enable the Loki charm to specify the host address and the path of the LokiPushApi endpoint.

**Note**: The path of the LokiPushApi endpoint will be affected by an ingress using a path routing rule, see e.g. https://github.com/canonical/traefik-k8s-operator#configurations

**Note**: The future charming of Loki using the distributed mode, will instead use the [https://github.com/canonical/traefik-k8s-operator/blob/main/lib/charms/traefik_k8s/v0/ingress.py](https://github.com/canonical/traefik-k8s-operator/blob/main/lib/charms/traefik_k8s/v0/ingress_per_unit.py) library and the respective ingress relation interface, as the Loki ingester components are designed to be load-balanced, rather than exposed as separate endpoints.

### To Reproduce

None

### Environment

- juju
- microk8s

### Relevant log output

```shell
None
```

**Comment by Abuelodelanada** [comment]
Hi @simskij @mmanciop 


Working in this I have some doubts.

You say that: *"The URL received by Loki must be used to produce the URL of the Loki Push API endpoint"*, but when Loki relates to Traefik, should `LokiPushApiProvider` differentiate between charms that are inside the same model and charms that are in other models?
For instance, let's say that Loki and Grafana Agent charms are related in the same model. Right now Grafana agent is receiving a list with dictionaries containing Loki local URLs:
```python
[
    {"url": "http://loki-0.loki-endpoints.model_name.svc.cluster.local:3100/loki/api/v1/push"},
    {"url": "http://loki-1.loki-endpoints.model_name.svc.cluster.local:3100/loki/api/v1/push"},
    {"url": "http://loki-2.loki-endpoints.model_name.svc.cluster.local:3100/loki/api/v1/push"},
    ...
]
```

With this implementation, should Grafana Agent (in the **same model**) receive the URL provided by Traefik too? 

I tend to think the answer is yes because you say: *"LokiPushApiProvider must therefore be updated to enable the Loki charm to specify the host address and the path of the LokiPushApi endpoint"*. I prefer not to guess though.

Reviewing the code I also realized that the `_endpoints()` method in `LokiPushApiProvider` should be re-factored too to fix the issue it has and to address the new functionality, see [#117](https://github.com/canonical/loki-k8s-operator/issues/117)

**Comment by mmanciop** [comment]
> With this implementation, should Grafana Agent (in the same model) receive the URL provided by Traefik too?

Yes, we have no special mechanism right now to decide if the requester is in the same model on not. We _could_ implement it so that, if the remote application has a name like `remote-*`, then it is a CMR, and thus, **to be safe**, it must go over the ingress.

Note that, in principle, nobody says that the two models are not on the same K8s cluster. Our guidance is not to put any other model on the COS K8s cluster, but the relation interface design should be more general than that.
