### ISSUE TITLE
Remove redundant Aggregator Topology and rename ProviderTopology

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#130]
### Bug Description

1. The Loki library includes `AggregatorTopology` however it is not used anywhere by this library and there is no clear use case for it either. Hence this object can be removed from the Loki charm library.
2. It is a bit counter intuitive to see `self.topology = ProviderTopology.from_charm(charm)` in the `ConsumerBase` class of Loki charm library. Should there be a `ConsumerTopology` instead ?

### To Reproduce

NA.

### Environment

NA.

### Relevant log output

```shell
NA
```

**Comment by simskij** [comment]
With the upcoming move of `JujuTopology` to its own library, I don't think we'll want to keep any of them.
