### ISSUE TITLE
Loki push API consumer does not handle pebble ready event

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#133]
### Bug Description

The Loki push API consumer object does not handle pebble ready event. This could lead to a potential bug if the consumer receives a relation changed event when pebble is not ready. Such a bug was reported for the provider in issue #128. Shouldn't the consumer also handle the pebble ready event ?

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

**Comment by rbarry82** [comment]
The consumer does not directly manipulate containers, and only needs to pull `loki_endpoints`, which will presumably be done as part of the configuration for any given consumer charm once Pebble _is_ ready. Did I miss something?

**Comment by dstathis** [comment]
I agree with @rbarry82 here. As the library does not access the container, this should not be an issue.
