### ISSUE TITLE
LokiPushApi related upgrade event integration tests is missing essential checks

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#136]
### Bug Description

At present there are three integration tests in Loki in the file `tests/test_upgrade_charm.py` (one of which keeps failing due to a known issue). These tests are

1. Deploy Loki from charmhub then refresh it from a locally built charm and check Loki is active
2. Deploy Alertmanager and Grafana from charmhub and add a relation with the Loki Deployed above in step 1.  Refresh Loki again using the same locally built charm and check Loki is active.
3. Scale the deployed Loki (from step 1 and 2) to have more than one unit and refresh it again using the same locally built charm and check Loki is active.

Shouldn't the integration tests for Loki's upgrade event handler be testing use cases such as 

1. Loki continues to aggregate Logs from the same clients it was related to prior to upgrade.
2. Continuity of Logs (labels) is not broken after upgrade.
3. Upgrading Loki-Tester allows for the injection of new alert rules.
4. Upgrading Loki-Tester allows for the removal of old alert rules.

There certainly may be many more use cases. However the above observations do make the case that the current upgrade integration tests are not only redundant (because all of them only test if Loki is active after upgrade) but also they do not to test the key aspects of the upgrade event handling process that are vital. In view of the above it is proposed to replace these three tests with *at least* one new tests. The proposed new test is 

- Deploy Loki from charmhub, Loki-Tester (locally built) and relate them.
- Check Loki aggregates logs and alerts fire (obviously also check Loki is active before doing this).
- Upgrade Loki with locally built charm.
- Check Loki still aggregates logs and there is continuity of Loki-Tester logs (and of course check Loki is active before doing this).
- Check Alerts still fire.

In addition the test may be extended to check alert rules can be added and removed on upgrade as follows

- Deploy Loki (from anywhere), Loki-Tester (locally built) and relate them (this can be a continuation of the test described above).
- Ensure Loki Tester is instrumented with one alert rule and submits logs to make this alert rule fire
- Check Loki aggregates logs and alerts rules fire
- Instrument Loki Tester to add a new alert rule and remove the old one
- Upgrade Loki Tester
- Instrument Loki Tester to push logs that would have resulted in both alert rules firing.
- Check that only the new alert rule is firing and not the old one.

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

### Additional context

NA

**Comment by sed-i** [comment]
> 1. Loki continues to aggregate Logs from the same clients it was related to prior to upgrade.
> 2. Continuity of Logs (labels) is not broken after upgrade.

This sounds like testing loki itself, and that a unit test would suffice perhaps?

> 3. Upgrading Loki-Tester allows for the injection of new alert rules.
> 4. Upgrading Loki-Tester allows for the removal of old alert rules.

I think this can be captured in a unit test. Am I missing something?

> the current upgrade integration tests are not only redundant (because all of them only test if Loki is active after upgrade)

The assertion on "Loki is active" is not the main test. The main test is that we don't have units in error. This test is similar to what @mmanciop was doing manually.

**Comment by balbirthomas** [comment]
Sure if some of these can be implemented in unit tests, then they are better as unit tests if they do not require mocking too much of the critical charm logic.

The continuity of logs on pod churn (IP change) or charm upgrade depends on topology labels. Is it enough to check the topology labels are the same after pod churn or charm upgrade ?  I mean does emitting a upgrade event by test harness have the same effect on Topology as an actual upgrade event or pod churn. If yes the unit test should do. If no then we may need an integration test. Also is "continuity of logs" a key product feature where we want an assurance that we never accidentally break it ? Could it break due to changes in Juju, Operator Framework, or even Kubernetes and if so is a unit test sufficient here ?

Also is there a scope to reduce the number of integration tests after rethinking the value of each of them and in the least document the key product feature they provide an assurance for. So for example it was not clear why we need to test upgrade with both single unit and multiple units ? Or rather why would one expect there to be a difference in the two cases. If it is the fact one unit may be leader and the other not. Then this difference of behavior could be detected through a unit test too. Is it sufficient to test Loki charm maintains continuity of logs on upgrade of a single unit of both Provider and Consumer ?

Also consider "checking loki alert rules actually fire when logs with errors are ingested" which has been implemented. Should we consider this testing Loki and not the charm so it may be removed or should it be treated as the minimal sanity test checking that the Loki charm provides Loki functionality like any other Loki install method (and that changes in dependencies have not broken this minimal functionality) ?

**Comment by rbarry82** [comment]
`JujuTopology` is more or less a given which does not depend in any real way on charm upgrade, pod name, or pod IP. It was explicitly designed this way, and outside of `juju_unit` (which may change on scale up/scale down), the rest of these are more or less a "given" unless Loki fundamentally changes/breaks the way labels are managed (similar to Prometheus).

The added tests will cover this case, though. Upgrading to charmhub versions is essentially scoped out here until such time as we have a breaking API change that we care about, since a local refresh will cover it meaningfully enough without worrying about additional network traffic.

Rebuilding `loki-tester` to include different alert rules is also scoped out, more or less to avoid yet another charm build in the integration test suite, but also because "what happens when alert rules for Loki change" can be adequately covered by adding `cos-config` back in for that specific purpose.
