### ISSUE TITLE
Loki Charm library should not handle updating alert rules in workload container

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#146]
### Bug Description

At present the `LokiPushApiProvider` library has methods such as `_remove_alert_rules()`, `_generate_alert_rules()` . These methods modify alert rule files in the workload container of the Loki Charm. This violates current practice of maintaining a separation of concern between charm libraries and charms whereby charms manage their workloads and charm libraries manage relation data. 

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

### Additional context

NA

**Comment by balbirthomas** [comment]
If this proposed refactor is accepted then refactoring `_check_alert_rules()` concomitantly may be necessary. This method should differentiate between the following cases in the information provided to the Provider charm
- Loki server was successfully contacted and there are no errors in alert rules
- Loki server was successfully contacted and errors were found in the alert rules
- Loki server was successfully contacted and no alert rules were found
- There was a failure to contact the Loki server

**Comment by Abuelodelanada** [comment]
I fully agree with the principle: _"maintaining a separation of concern between charm libraries and charms whereby charms manage their workloads and charm libraries manage relation data"_

That been said, from my point of view if we do not place `_remove_alert_rules()`, `_generate_alert_rules()`, `_check_alert_rules()` methods in the library, we have to place these functionalities in the charm side. If we place them in the charm side, charm authors that want to use this lib, will have to implement these methods by themself.

If this is correct we will violate our other principle for libs: _"Write libs that are easy to use. Just fetch the lib, import it, instantiate it and voilà!"_

Is that correct or am I missing something here?

**Comment by balbirthomas** [comment]
Yes indeed charms will have to write alert rules to their workloads themselves. This is how the Prometheus charm does it. The charm library should provide a public method to retrieve the alert rules. The charm library *may also* provide a public method that validates the alert rules using address of Loki server as an input. 

This ticket and the above observations are only suggested considerations for future refactors. The Loki charm developers may have a deeper understanding if these suggestions are appropriate for their charm and hence I trust their better judgement on what is appropriate.
