### ISSUE TITLE
Loki config's `instance_addr` should be set even without a `loki_push_api` relation

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#159]
## Bug Description
Currently, when Loki is deployed without a `loki_push_api` relation, the [config file](https://grafana.com/docs/loki/latest/configuration/) has no `instance_addr` set.

ALSO, the config file is recreated ONLY if `loki_provider.on.loki_push_api_alert_rules_changed` is emitted, which shouldn't be the case: the config file should be re-created regardless.

## To Reproduce
```shell
$ juju deploy --channel=edge loki-k8s loki
$ microk8s.kubectl exec -n mymodel loki-0 -c loki -- cat /etc/loki/local-config.yaml | grep instance_addr
    instance_addr: null
```

## Expected behavior
- There should be an address even if loki is deployed in isolation.
- Need to take ingress into account.
- Iiuc, taking the first relation's bind address doesn't make sense because technically there could be a different bind address per relation.

## Additional context
The address is taken from the lib:
https://github.com/canonical/loki-k8s-operator/blob/3fb83f9350f7a55ca1976015303f965a26227082/src/charm.py#L225

and the lib expects to have a `"public_address"` already present in relation data:
https://github.com/canonical/loki-k8s-operator/blob/3fb83f9350f7a55ca1976015303f965a26227082/lib/charms/loki_k8s/v0/loki_push_api.py#L1387-L1392

but `"public_address"` is only set on rel-changed:
https://github.com/canonical/loki-k8s-operator/blob/3fb83f9350f7a55ca1976015303f965a26227082/lib/charms/loki_k8s/v0/loki_push_api.py#L1295-L1297

**Comment by rbarry82** [comment]
The easy workaround here is to just use `127.0.0.1` or `0.0.0.0` if nothing is set.

The ingress address will be the same for every relation until when/if we get to a point that Multus, DPDK, or some other solution makes it in. Even if it does, the odds of it going all the way to Loki are pretty low on k8s. one_pod:one_ip_addr is a fair baseline assumption.
