### ISSUE TITLE
Build and release Static Promtail for ARM64

### ISSUE THREAD

**Issue by balbirthomas** [canonical/loki-k8s-operator#163]
### Bug Description

At present a static Promtail for ARM64 platform has not been released to this github repository. The purpose of this ticket is to update the release page with static promtail for ARM64, along with sha256 sums. Also update to `PROMTAIL_BINARIES` in Loki Push API library may be required.

This requires 
1. Update to [github runners](https://github.com/canonical/loki-k8s-operator/blob/main/.github/workflows/build-promtail-release.yaml)
2. It may also be useful to ensure the github runners generates an additional artifact that contain SHA256 sums for all relased binaries and the gziped files of these binaries.

### To Reproduce

NA

### Environment

NA

### Relevant log output

```shell
NA
```

### Additional context

NA

**Comment by simskij** [comment]
Done.
