### ISSUE TITLE
Collect logs from multiple containers in the same pod

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/loki-k8s-operator#186]
### Enhancement Proposal

There's no straightforward way to set up the loki `LogProxyConsumer` to work with multiple containers in the same charm. Instantiating it more than once is not supported either:
`RuntimeError: two objects claiming to be IndicoOperatorCharm/LogProxyConsumer[log-proxy] have been created`

It is my understanding that this is a very common use case and it should be supported.

**Comment by simskij** [comment]
This is something we need to support. Maybe not in the GA, but at least in a point release soon thereafter. I envision that we'll keep the single instantiation and add a way for authors to pass multiple containers with multiple, different, log configs.
