### ISSUE TITLE
Loki does not provide the ingress address over the prometheus_scrape relation

### ISSUE THREAD

**Issue by dstathis** [canonical/loki-k8s-operator#210]
### Bug Description

Loki sends it's internal address to prometheus rather than it's ingress address.

### To Reproduce

* Deploy Loki, Prometheus, and Traefik
* Relate Loki -> Traefik and Loki -> Prometheus
* Check targets page in prometheus UI

### Environment

Ubuntu 22.04
Juju latest/stable

### Relevant log output

```shell
-
```

### Additional context

![image](https://user-images.githubusercontent.com/2110777/196456064-f66efc4c-653d-40ad-ac4a-208cfaabf3a4.png)

**Comment by simskij** [comment]
Relates to https://github.com/canonical/loki-k8s-operator/issues/187
