### ISSUE TITLE
Support HTTPS for log ingestion

### ISSUE THREAD

**Issue by simondeziel** [canonical/loki-k8s-operator#221]
### Enhancement Proposal

The LXD team uses the `LokiPushApiConsumer` interface from the `charms.loki_k8s.v0.loki_push_api` library. This provides us with a list of URL endpoints to push logs to. ATM, the endpoints only support HTTP and we would like to use HTTPS.

We deploy Loki using the COS lite bundle which means the Loki endpoint URL we currently receive looks like this:

`http://10.76.66.104:80/cos-loki-0/loki/api/v1/push`

When implementing HTTPS, the consumer side (LXD here) will need more information to validate the Loki HTTPS server. Depending on how this is implemented, a CA certificate may need to be included in the relation data. Alternatively, a self-signed server cert with the appropriate IP/DNS SANs might be sufficient.

**Comment by simskij** [comment]
We're currently working on adding HTTPS termination to Traefik. Once we have that, this should work out of the box.

**Comment by simskij** [comment]
Loki will need to communicate that it's now terminated using https, and communicate the cert to the consumer.

**Comment by simskij** [comment]
TLS is now available both with termination at the ingress and for end-to-end encryption within the cluster.
