### ISSUE TITLE
Handling of rule files is outdated

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#223]
Loki's handling of rule files is outdated. At the very least there's https://github.com/canonical/prometheus-k8s-operator/pull/400.

https://github.com/canonical/loki-k8s-operator/blob/ac1c74794c44e890c523cc73b85f231f6e56aa4d/lib/charms/loki_k8s/v0/loki_push_api.py#L865

Currently the same alert rules handling logic is used in prometheus-scrape, remote-write and loki-push-api. We should probably move alert rule handling to observability libs.

**Comment by rbarry82** [comment]
Done
