### ISSUE TITLE
Promtail build fails repeatedly (again)

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#242]
### Bug Description

The "Check for new Promtail releases" actions fails repeatedly.

### To Reproduce

Run [workflow](https://github.com/canonical/loki-k8s-operator/actions/workflows/check-promtail-releases.yaml).

### Environment

GH runner.

### Relevant log output

```shell
/app/promtail: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /app/promtail)
```

**Comment by lucabello** [comment]
This should be solved by upgrading the golang version.

**Comment by rbarry82** [comment]
Done
