### ISSUE TITLE
I would consider delegating this concern to a separate class, for example

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#27]
I would consider delegating this concern to a separate class, for example
```python
alerts = list(map(LokiAlertRule.from_file, Path(self._alert_rules_path).glob("*.rule")))
```

_Originally posted by @sed-i in https://github.com/canonical/loki-operator/pull/25#discussion_r727433750_

**Comment by Abuelodelanada** [comment]
Also: Too deep nesting.

**Comment by simskij** [comment]
Issue is stale and the original code is no longer present in `HEAD`. Closing.
