### ISSUE TITLE
Logging multiple containers does not work.

### ISSUE THREAD

**Issue by gtrkiller** [canonical/loki-k8s-operator#307]
### Bug Description

When trying to implement Loki logging with multiple k8s containers, this seems not to be possible at all.

### To Reproduce

Declare two LogProxyConsumer objects in the same relation like [this](https://pastebin.canonical.com/p/cQXnySX88y/)
and it will fail like [this](https://pastebin.canonical.com/p/S3pd3YZspG/) when the consumer charm is deployed (no relation to cos-lite required for the failure to be seen)

If you want, you can also add new relations for every other container you want to log, and declare them as separate LogProxyConsumers (one for each relation, like [here](https://pastebin.canonical.com/p/6t2C5PTCzb/)) and then the charm will fail like [this](https://pastebin.canonical.com/p/dwn3TPZpfB/) after relating both relations to loki's logging like [here](https://pastebin.canonical.com/p/kZJGXGj39f/). It seems only one binding is accepted.

### Environment

Juju 3.1.5 is ran locally with microk8s 1.28 strict.

### Relevant log output

```shell
Logs in the To Reproduce section.
```

**Comment by Abuelodelanada** [comment]
Hi @gtrkiller 

Which charm with multiple containers are you using?

**Comment by gtrkiller** [comment]
The charm I used to test this was [Indico](https://github.com/canonical/indico-operator) with the modifications stated previously.
