### ISSUE TITLE
`charms.observability_libs.v0.juju_topology` lib is deprecated

### ISSUE THREAD

**Issue by simondeziel** [canonical/loki-k8s-operator#310]
### Enhancement Proposal

https://github.com/canonical/observability-libs/blob/main/lib/charms/observability_libs/v0/juju_topology.py#L89-L94:

```
class JujuTopology:
    """JujuTopology is used for storing, generating and formatting juju topology information.

    DEPRECATED: This class is deprecated. Use `pip install cosl` and
    `from cosl.juju_topology import JujuTopology` instead.
    """
```

Other bits of the observability stack moved to `cosl` already so it'd be great for Loki to do the same.

**Comment by sed-i** [comment]
I was just thinking the same. Thanks for filing the issue!
