### ISSUE TITLE
latest/stable revision 112 on charmhub still uses old revision: 88 

### ISSUE THREAD

**Issue by Guillaumebeuzeboc** [canonical/loki-k8s-operator#351]
The latest/stable is still using the loki-image revision 88: https://charmhub.io/loki-k8s/resources/loki-image

This image embed loki 2.4.1  which is incompatible with the [embedded_cache](https://github.com/canonical/loki-k8s-operator/blame/main/src/config_builder.py#L162) configuration added in the charm.

This causes the charm to fail starting. 
Trying to start manually loki from within the container gives:
```
failed parsing config: /etc/loki/loki-local-config.yaml: yaml: unmarshal errors:
  line 4: field embedded_cache not found in type cache.Config
  line 37: field embedded_cache not found in type cache.Config
```

Forcing the use of the revision 91 for the loki-image solves the problem.

**Comment by mmkay** [comment]
Hi @Guillaumebeuzeboc! The revision was updated on March 15 to use revision 92 so the issue should now be fixed.
