### ISSUE TITLE
What about having a tester charm in charmhub?

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#365]
Out-of-scope:
A tester charm for logging is so useful we should probably have it on charmhub.
Could augment [flog-k8s](https://charmhub.io/flog-k8s) or just use this one as a base.

_Originally posted by @sed-i in https://github.com/canonical/loki-k8s-operator/pull/364#discussion_r1521837647_

**Comment by dstathis** [comment]
This would likely be a generic cos-tester charm. This charm would be similar to flog but with all of our interfaces.

**Comment by dstathis** [comment]
We should consider that flog and avalanche might already serve this purpose. The scope of this issue will be to determine if we need to create anything else and if so, create new issues for things we need to build.

**Comment by simskij** [comment]
Having flog and avalanche available as separate tester charms make them easier to maintain and less complex to orchestrate. Closing issue.
