### ISSUE TITLE
Logs are replayed on pebble replan

### ISSUE THREAD

**Issue by markbeierl** [canonical/loki-k8s-operator#382]
### Bug Description

https://warthogs.atlassian.net/browse/TELCO-1130 describes a problem we had where the charm replanned the layers on every status refresh. Admittedly the charm was in error here, however the observed behaviour with Loki might not be as indended.

Essentially on every replan, the logs for the container get replayed to Loki with the current timestamp.

### To Reproduce

1. Write a charm that is integrated with logging, and calls replan after merging the same layer
2. Note the replay of pebble logs from the workload container on each call to replan

### Environment

Juju 3.4
Micrkok8s 1.29-strict
Loki receiver: loki               2.9.4    active      1  loki-k8s               latest/stable
Charm lib: lib/charms/loki_k8s/v1/loki_push_api.py 
* LIBID = "bf76f23cdd03464b877c52bd1d2f563e" 
* LIBAPI = 1
* LIBPATCH = 8

### Relevant log output

```shell
Screenshot attached
```

### Additional context

Here is an example of output, with the date of the original log message as part of the payload. We can see it was re-emitted and logged to Loki on 2024-04-18, and the original log message was generated on 2024-04-15.
![image](https://github.com/canonical/loki-k8s-operator/assets/19839294/a19b9801-65dc-423d-8d45-4edf89c29963)

**Comment by ca-scribner** [comment]
Hey @markbeierl, what charm is this for?  Can you provide a repro case so we can dig into it?

**Comment by dstathis** [comment]
Not sure if this is still an issue. Feel free to reopen if this still happens.
