### ISSUE TITLE
LogForwader doesn't handle alert rules

### ISSUE THREAD

**Issue by saltiyazan** [canonical/loki-k8s-operator#403]
### Bug Description

`LogForwarder` in `loki_push_api` doesn't put the alert rules to relation data.
I was trying to set some logging alert rules in vault-k8s that uses `LogForwarder` to forward its logs to Loki through grafana-agent. I couldn't find the alert rule in Grafana, doing some debugging I could not find the alert rules nor the path to the alert rules in the relation data.
I looked at the code and found that `LogForwarder` doesn't do much with the alert rules path it receives in the init function.

Only the `_handle_alert_rules` function puts the alert rules to relation data and `LogForwarder` doesn't call that function.

### To Reproduce

I faced this issue during development, while I was trying to add Loki alert rules to vault-k8s that uses `LogForwarder`, the rule I added looked like [this](https://pastebin.canonical.com/p/Nt2JYbk539/) and I added it under the default path used in the lib, this is not published to charmhub but any trying to add log alert rules to any charm that uses `LogForwarder` should have the same result.

1. Deploy your charm that uses `LogForwarder` and has log alert rules, let's call <your-charm>
2. `juju deploy cos-lite --trust`
3. `juju deploy grafana-agent-k8s`
4. `juju integrate <your-charm>:logging grafana-agent-k8s`
5. `juju integrate loki:logging grafana-agent-k8s:logging-consumer`
6. `juju show-unit <your-charm>/0`
7. `juju show-unit grafana-agent-k8s/0`

Alert rules are not in the relation data.

### Environment

LIBAPI = 1 LIBPATCH = 10

### Relevant log output

```shell
N/A
```

**Comment by dstathis** [comment]
We need to call [`_handle_alert_rules`](https://github.com/canonical/loki-k8s-operator/blame/5dd8dc8d382093d6dbf18d792f59776704355d25/lib/charms/loki_k8s/v1/loki_push_api.py#L1542) in LogForwarder.

**Comment by gruyaume** [comment]
@dstathis what is the status of this issue? This is preventing adding alert rules in charms.

**Comment by michaeldmitry** [comment]
Hi @gruyaume
This is now fixed in the newest library `LIBPATCH=13`
