### ISSUE TITLE
Instantiating the library with alert rule paths as relative paths will break it

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#47]
Commenting here so it's close, since I missed the last review, but as happy as I am to see a nested function as `_group_name`, I suppose it should be moved out since we decided not to use this as a pattern.

Sorry in advance, since this is long for a part of the library which isn't even *in* this PR.

`def _group_name(path) -> str:` should be top-level (and then typing it as `typing.Union[Path.PosixPath, Path.WindowsPath]`) wouldn't hurt. and using `path.relative_to`

Also:

```
return "{}_{}alerts".format(
    topology.identifier, "" if relpath == "." else relpath.replace(os.path.sep, "_") + "_"
)
```

This hurts to parse.

This is a nit, really, and I hate commenting on committed code, but it _is_ a nested function, and as long as it's being moved, it could look nicer. `os.path` is ok, but the format is definitely a place where it's not intuitive when `+ "_"` is actually applied, and re-reading it to grok it is slow. It looks like a smell, and the double `)` from `.format()` and `.replace()` makes me worry that later patches could subtly break it.

Arguably, the current formatting is a fragile, since relative paths with "../" or something, absolute paths will lead to `__`, this would not work on any Windows charms, as a library function in the proxy, etc. May as well code defensively as long as I'm looking at it.

It would be very possible, right now, to get a string like the following on Windows (or just keep the `..` part on Linux), and that may be an ugly bug.

`{topology.identifier)_C:_foo_.._bar_baz_alerts`

Pathlib ends up being somewhat more verbose, but much more flexible/resilient. Even if it isn't used, we should absolutely strip out `../` and `^([A-Z]+:)?/` with a regex and stick with the rest of `os.path`.

```
relpath = path.parent.relative_to(dir_path)

# We should account for both absolute paths and Windows paths. Convert it to a POSIX
# string, strip off any leading /, then join it

if relpath.samefile(Path(".")):
    path_str = ""
else:
    # Get rid of leaving / and optionally drive letters so they don't muck up the template later,
    # since Path.parts returns them. The 'if relpath.is_absolute ...' isn't even needed since re.sub
    # doesn't throw exceptions if it doesen't match, so it's optional, but it makes it clear what we're
    # doing.
    
    # Note that Path doesn't actually care whether the path is valid just to instantiate the object, so
    # we can happily strip that stuff out to make templating nicer
    relpath = Path(re.sub(r'^([A-Za-z]+:)?/', '', relpath.as_posix()) if relpath.is_absolute() else relpath
    
    # Get rid of relative path characters in the middle which both os.path and pathlib leave hanging
    # around. We could use path.resolve(), but that would lead to very long template strings when
    # rules come from pods and/or other deeply nested charm paths
    char_filter = lambda x: x not in ["..", "/"]
    path_str = "{}_".format("_".join(filter(char_filter, relpath.parts)))

return "{}_{}alerts.format(
    topology.identifier, path_str
)
```

_Originally posted by @rbarry82 in https://github.com/canonical/loki-operator/pull/45#discussion_r762172941_

**Comment by rbarry82** [comment]
No worries. Never meant to block on this (too bad Github doesn't let me leave comments that don't have to be resolved somehow).

OF does, in principle, support Windows, so the safety is probably good futureproofing

**Comment by sed-i** [comment]
Similar consideration for prom
https://github.com/canonical/prometheus-operator/blob/4299736c068a817f77e780c404430f44f2ef0363/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L681

In fact, maybe better to first fix in prom, in which the encompassing logic is more recent than loki's.
