### ISSUE TITLE
Change property contract

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#49]
This property now may return:
- A list
- A string
- None

Maybe a better contract for consumes will be a property that always returns a **list**:

- A list with many elements
- A list with one element
- An empty list

_Originally posted by @Abuelodelanada in https://github.com/canonical/loki-operator/pull/48#discussion_r763512319_

**Comment by mmanciop** [comment]
I thought about it, but frankly is makes semantically little sense to return a singleton list is the relation has `limit: 1` set.

**Comment by Abuelodelanada** [comment]
That's true.
I was thinking in the implementation in consumer side, that will be easy since will always be the same, no matter if you have a relation with 1 or n Loki.
