### ISSUE TITLE
Logging incorrectly states that the alert rules have been saved to disk

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#53]
If this is in past tense then should probably be under `_generate`?

_Originally posted by @sed-i in https://github.com/canonical/loki-k8s-operator/pull/48#discussion_r764059578_

**Comment by simskij** [comment]
**TL;DR**

We are currently saying that we **haved saved**, although the actions have not been performed yet. In case it errors, the operator will likely be **very** confused by reading the logs.
