### ISSUE TITLE
Log proxy does not install promtail on charm upgrade

### ISSUE THREAD

**Issue by dstathis** [canonical/loki-k8s-operator#60]
Title says it all. This should probably be done at the same time as we merge the two libraries.

**Comment by dstathis** [comment]
This actually happens anytime a pod is redeployed. We should probably fix this by observing the `on_pebble_ready` event in the lib.

**Comment by jnsgruk** [comment]
> This actually happens anytime a pod is redeployed. We should probably fix this by observing the `on_pebble_ready` event in the lib.

We probably should use `on_pebble_ready`, though with a guard so that the code only runs if the relevant relation is established?

**Comment by simskij** [comment]
Solved in #74
