### ISSUE TITLE
LokiPushApi events review

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#65]
Shouldn’t `LogProxyConsumer` also observe `relation_broken` for safety? Also it needs `relation_joined` for new consumer units being spun up, e.g., after a pod churn, as those do not get the `relation_created`, and I am not sure `relation_changed` will fire.

`LokiPushApiProvider`: alert rules probably should be deleted on `relation_broken`: relation_departed is for single units going away, but alert rules are global to the consumer Juju app. Also, same comment about `relation_joined` applies.

_Originally posted by @mmanciop in https://github.com/canonical/loki-k8s-operator/issues/63#issuecomment-1007194880_

**Comment by simskij** [comment]
Will possibly lead to buggy behavior. This issue is still present in the current `HEAD`.

**Comment by rbarry82** [comment]
Reducing the scope of this to `LokiPushApi` only.

`LogProxyConsumer` listens to `pebble_ready`, which covers churn/upgrades.

When unit data bag changes happen for endpoints, let's re-evaluate whether `relation_broken` is needed there.

In `relation_departed`, `LogProxyConsumer` already checks for the presence of a valid relation and stops, and also checks if there are no endpoints, which _may_ cover this case.
