### ISSUE TITLE
Add integration test for `LogProxyConsumer`

### ISSUE THREAD

**Issue by simskij** [canonical/loki-k8s-operator#77]
What, no integration test? :-)

_Originally posted by @mmanciop in https://github.com/canonical/loki-k8s-operator/issues/72#issuecomment-1015108909_

**Comment by sed-i** [comment]
I wonder if this needs to be an itest.

For an itest I would:
1. Add an "always firing" alert to [flog-k8s](https://github.com/sed-i/flog-k8s-operator/).
2. Relate loki to flog. Perhaps also loki to alertmanager.
3. Query the `localhost/loki/prometheus/api/v1/alerts` endpoint and perhaps the alertmanager active alerts endpoint.

However, all of the above is already covered separately in:
- [unit/test_log_proxy_consumer](tests/unit/test_log_proxy_consumer.py)
- [integration/test_multiple_rule_providing_apps](tests/integration/test_multiple_rule_providing_apps.py)
- [integration/test_alert_rules_fire](tests/integration/test_alert_rules_fire.py)

I propose to close this issue without further action.
@simskij @mmanciop @rbarry82 @Abuelodelanada @balbirthomas @dstathis

**Comment by rbarry82** [comment]
Considering that we actually _do not_ have an integration test for `LogProxyConsumer` at all, it's probably a good safeguard to have, especially as we twiddle the architecture.
