### ISSUE TITLE
Promtail is currently hard-coded to amd64. Needs to support arm64 as well

### ISSUE THREAD

**Issue by simskij** [canonical/loki-k8s-operator#83]
See https://github.com/canonical/loki-k8s-operator/blob/cc073c4f9aeb79255b598e0230aa62a2384bcfab/lib/charms/loki_k8s/v0/loki_push_api.py#L454-L466

**Comment by balbirthomas** [comment]
After discussion with @simskij an additional requirement is that the LogProxyConsumer should be able to detect if the Consumer charm is providing a Promtail resource and in this case the Promtail binary should not be downloaded from the release page. This allows for air gapped deployments.

**Comment by rbarry82** [comment]
@balbirthomas closed in #158 ?

**Comment by balbirthomas** [comment]
Closing this since we have extensibility to add new architectures but are lacking binaries to do so. I created #163 to track upload of new binaries and update Loki library.
