### ISSUE TITLE
loki_push_api does not like loki_alert_rules being an empty file.

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/loki-k8s-operator#98]
`_is_official_alert_rule_format(rule_file)`
raises an uncaught `TypeError: argument of type 'NoneType' is not iterable`
when loki_alert_rules is an empty file. 

Is that a valid 'rules' file to begin with?
Either way, looks like we should return `list()` in `_from_file` even if the file is invalid/empty.

**Comment by PietroPasotti** [comment]
note: underlying issue is that `yaml.safe_load(stream)` can and does return `None` in this case.

**Comment by Abuelodelanada** [comment]
Thanks for the report Pietro!
